---
# Install and setup tasks
- name: install postgresql
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ postgresql_packages }}"

- name: ensure postgresql is started
  service:
    name: "{{ postgresql_service }}"
    enabled: yes
    state: started

- name: install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ dependencies_packages }}"

- name: install web backend tools
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ web_backend_packages }}"
  when: netbox_setup_web_backend

- name: install web frontend tools
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ web_frontend_packages }}"
  when: netbox_setup_web_frontend