---
- include: include-vars.yml

- include: install-packages.yml

- include: setup-database.yml

- include: setup-netbox.yml

- include: setup-web-backend.yml
  when: netbox_setup_web_backend

- include: setup-web-frontend.yml
  when: netbox_setup_web_frontend