---
- name: install gunicorn
  pip:
    name: gunicorn
    extra_args: "--upgrade"
    virtualenv: "{{ netbox_virtualenv_path }}"
    virtualenv_command: "{{ netbox_python_binary }} -m venv"
  become: true
  become_user: "{{ netbox_user }}"
  register: pip_result
  until: pip_result is success

- name: configure gunicorn
  template:
    src: gunicorn_process.sh.j2
    dest: "{{ netbox_user_home_directory }}/gunicorn_process.sh"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    mode: 0755
  notify:
    - restart netbox

- name: configure rqworker
  template:
    src: rqworker_process.sh.j2
    dest: "{{ netbox_user_home_directory }}/rqworker_process.sh"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    mode: 0755
  notify:
    - restart netbox
    - restart netbox rqworker
  when: (netbox_config.WEBHOOKS_ENABLED is defined)
        and (netbox_config.WEBHOOKS_ENABLED|bool == true)

- name: configure supervisord (netbox)
  template:
    src: netbox.conf.j2
    dest: "{{ netbox_supervisord_config_directory }}/netbox.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart netbox

- name: configure supervisord (rqworker)
  template:
    src: netbox-rqworker.conf.j2
    dest: "{{ netbox_supervisord_config_directory }}/netbox-rqworker.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart netbox
    - restart netbox rqworker
  when: netbox_config.WEBHOOKS_ENABLED is defined

- name: ensure supervisord is started
  service:
    name: "{{ netbox_supervisord_service }}"
    state: started
