---
- name: install gunicorn
  pip:
    name: gunicorn
    extra_args: "--upgrade"
    virtualenv: "{{ netbox_virtualenv_path }}"
    virtualenv_command: "{{ netbox_python_binary }} -m venv"
  become: true
  become_user: "{{ netbox_user }}"

- name: configure gunicorn
  template:
    src: gunicorn_process.sh.j2
    dest: "{{ netbox_user_home_directory }}/gunicorn_process.sh"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    mode: 0755
  notify:
    - restart netbox

- name: configure supervisord
  template:
    src: netbox.conf.j2
    dest: "{{ netbox_supervisord_config_directory }}/netbox.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart netbox

- name: ensure supervisord is started
  service:
    name: "{{ netbox_supervisord_service }}"
    state: started
