---
- name: ensure postgresql is ready
  service:
    name: postgresql
    state: started

- name: create postgresql database
  postgresql_db:
    name: "{{ netbox_database }}"
  become: true
  become_user: "{{ __netbox_postgresql_user }}"

- name: create postgresql user
  postgresql_user:
    name: "{{ netbox_database_user }}"
    password: "{{ netbox_database_password }}"
    encrypted: true
    db: "{{ netbox_database }}"
    priv: ALL
  become: true
  become_user: "{{ __netbox_postgresql_user }}"

- name: ensure redis is ready
  service:
    name: "{{ netbox_redis_service }}"
    state: started
