---
- name: Determine latest GitHub release (local)
  delegate_to: localhost
  become: false
  uri:
    url: "https://api.github.com/repos/netbox-community/netbox/releases/latest"
    body_format: json
  register: _github_release
  run_once: true
  until: _github_release.status == 200
  retries: 5

- name: Set netbox_version
  set_fact:
    netbox_version: "{{ _github_release.json.tag_name }}"
