---
- name: restart netbox
  supervisorctl:
    name: netbox
    state: restarted
  when: netbox_setup_web_backend

- name: restart apache2
  service:
    name: "{{ netbox_apache2_service }}"
    state: restarted
  when: netbox_setup_web_frontend
