---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      register: package_result
      until: package_result is success
      when: ansible_os_family == 'Debian'

  vars:
    netbox_setup_ldap_auth: true
    netbox_setup_web_backend: true
    netbox_setup_web_frontend: true

  roles:
    - role: ansible-role-netbox
